### ISSUE TITLE
在华为Mate30上，获取手机验证码会导致应用闪退

### ISSUE THREAD

**Issue by disymayufei** [MrXiaoM/Aoki#1]
我的手机型号为华为Mate30，在尝试登录时可以正常通过滑块验证，但是在获取手机验证码时会发生闪退，且多次尝试后依然如此。

**Comment by MrXiaoM** [comment]
`Android/data/top.mrxiaom.mirai.aoki/files/AokiMirai` 目录下有无 `crash.log`，有的话发上来。

**Comment by disymayufei** [comment]
net.mamoe.mirai.network.RetryLaterException: 今日操作次数过多，请等待一天后再试。
	at net.mamoe.mirai.internal.network.protocol.packet.login.SmsVerifyInfo.requestSms(WtLogin.kt:54)
	at net.mamoe.mirai.internal.network.protocol.packet.login.SmsVerifyInfo$requestSms$1.invokeSuspend(Unknown Source:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:966)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:293)
	at android.app.ActivityThread.main(ActivityThread.java:9551)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1204)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@50123af, Dispatchers.Main.immediate]

**Comment by disymayufei** [comment]
这样看来似乎是我的账号引发的问题，但是实际上应该通过弹窗提示给我这条消息，而非直接闪退崩溃

**Comment by disymayufei** [comment]
如果您需要我的账号作为测试，可以加我QQ：1481567451，我把我测试用的账号和密码给您

**Comment by MrXiaoM** [comment]
加了个 try catch，目前还没有时间去测试
